### ISSUE TITLE
preserve type="module" on scripts

### ISSUE THREAD

**Issue by dancrew32** [google/strict-csp#57]
One unexpected behavior of this plugin was that it removed script tag attributes that may be essential to the code running correctly. For example, my team was dealing with a third party script that required this format:

```html
<script async type="module" src="https://example.com/script.js"></script>
```

But the output of this strict-csp script only uses a few specific script attributes:
https://github.com/google/strict-csp/blob/bd192b4dbe96ba29bbc709d9f7fe2ee7efa9fab6/strict-csp/index.ts#L179-L183

It would be great to throw an error if there are attributes besides `async` that end up being dropped during this conversion.

Our workaround was to not use the script tag and run the following code to be CSP-compliant:

```javascript
const s = document.createElement('script');
s.src = scriptUrl;
s.type = 'module';
s.async = true;
document.body.appendChild(s);
```

**Comment by lweichselbaum** [comment]
We're preserving the "type" attribute now. Thank you for reporting this issue!

**Comment by dothem1337** [comment]
@lweichselbaum did you plan to release a new version to npm in the near future? There's still version 1.0.4 which is over 3 years old and doesn't include this change (and the DOCTYPE issue aswell).
