### ISSUE TITLE
Webpack-Plugin breaks doctype

### ISSUE THREAD

**Issue by empbd** [google/strict-csp#63]
The webpack plugin breaks the doctype of the documents:

With given input `<!DOCTYPE html>` it only returns `<!DOCTYPE >`, which results in quirks-mode in the browser.

In the method `serializeDom()` instead of calling `return this.$.html();` it should be calling `return this.$.root().html();` to preserve the doctype.

**Comment by empbd** [comment]
Workaround until the issue is fixed:
```
const strictCspLib = require('strict-csp')
strictCspLib.StrictCsp.prototype.serializeDom = function () {
  return this.$.root().html()
}
```

**Comment by lweichselbaum** [comment]
Just fixed the issue. Thank you very much for reporting!

**Comment by empbd** [comment]
Thank you for fixing!
